apiVersion: apps/v1
kind: Deployment
metadata:
  name: gidget
spec:
  selector:
    matchLabels:
      app: gidget
  replicas: 1
  template:
    metadata:
      labels:
        app: gidget
    spec:
      containers:
      - name: gidget
        image: andremor/gidget
        ports:
        - containerPort: 4500