const levelresponse = "You must be a verified user. Get level 2 in the server ranking for that. Check your level by going to <#608560264425635850> and putting `-level`"

let questions = ["who founded wuzzleburg", "who was the founder of Wuzzleburg", "when was wuzzleburg founded", "who is wubby", "where can i find Wubbzy episodes", "what is wubbzy's dream season", "sukangaroo", "how do i post", "how do i upload", "why can't i post", "why can't i upload", "who is mopsy", "who's mopsy", "who's wubby"];

let responses = ["Wuzzleburg was founded by Heinrich van Wuzzle", "Wuzzleburg was founded by Heinrich van Wuzzle", "Wuzzleburg was founded in 1853", { content: "It's the beta version of Wubbzy", files: ['https://cdn.discordapp.com/attachments/402555684849451030/640753924441243680/unknown.png']}, "You can buy them on YouTube or Amazon (as well as other stores), and enjoy high definition in each episode.\n\nIf you don't have money just search the web for that", "Is a fanmade season created by **SuKanzoo**.\nIs very interesting :)\nIt is still in beta and unfinished.\nhttps://wubbzyfanon.fandom.com/wiki/Wow!_Wow!_Wubbzy!_Dream_Season", {files: ['https://cdn.discordapp.com/attachments/608560264425635850/676627423575539732/unknown.png']}, levelresponse, levelresponse, levelresponse, levelresponse, { content: "Mopsy comes from the unpublished comic \"The Tail of Flopsy, Mopsy, and Ted\", this was the basis of the development of Wubbzy. Wubbzy was originally going to be called by that name, but due to legal problems, his name had to be changed to Wubby", files:[ "https://media.discordapp.net/attachments/402555684849451030/708922115998482453/unknown.png"]}, { content: "Mopsy comes from the unpublished comic \"The Tail of Flopsy, Mopsy, and Ted\", this was the basis of the development of Wubbzy. Wubbzy was originally going to be called by that name, but due to legal problems, his name had to be changed to Wubby", files: [ "https://media.discordapp.net/attachments/402555684849451030/708922115998482453/unknown.png"]}, { content: "It's the beta version of Wubbzy", files: ['https://cdn.discordapp.com/attachments/402555684849451030/640753924441243680/unknown.png']}];

module.exports = {
  questions,
  responses
}