name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and testing CI script
      run: docker build . --tag andremor/gidget
    - name: See image size
      run: docker images | grep "andremor/gidget"