name: Test code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing APT dependencies
      run: sudo apt-get update && sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libtool qrencode
    - name: Installing project dependencies
      run: npm install --legacy-peer-deps
    - name: Doing things with Discord.js
      run: npm i -g gen-esm-wrapper && cd ./node_modules/discord.js && gen-esm-wrapper ./src/index.js ./src/index.mjs
    - name: Executing CI test script
      run: npm test